-- 코드를 입력하세요
SELECT NewTable.ANIMAL_ID, NewTable.NAME 
FROM
(SELECT A.ANIMAL_ID, A.NAME, (B.DATETIME - A.DATETIME) AS Duration
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B 
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY Duration DESC) AS NewTable
LIMIT 2;
